### ISSUE TITLE
I wonder how to replace text with svg-path information.

### ISSUE THREAD

**Issue by GangHyeok-Ji** [RadekVyM/Navbar-Animation-2#1]
I'm studying well with the sauce you shared.

I was frustrated by putting webView on the navigation page, and thank you for the wonderful sharing.

I'm having a hard time changing the character at the bottom of the icon.

I wonder how to replace text with svg-path information.

I tried extracting it through inkscape. But the extraction is too long.

**Comment by RadekVyM** [comment]
Hi @GangHyeok-Ji,

unfortunately there is no way to get a path from a string in Microsoft.Maui.Graphics (or at least I was not able to find that). I used Inkscape too to get the paths.

In the Xamarin.Forms version of this app, I used SkiaSharp, which supports getting a path from a string. Maybe try to look at [that solution](https://github.com/RadekVyM/Navbar-Animation-2/blob/7cda52cc3747d847af8990f0043938d0592b24cd/src/NavbarAnimation2/NavbarAnimation2/Views/Controls/TabSvgView.xaml.cs).

**Comment by GangHyeok-Ji** [comment]
> Hi @GangHyeok-Ji,
> 
> unfortunately there is no way to get a path from a string in Microsoft.Maui.Graphics (or at least I was not able to find that). I used Inkscape too to get the paths.
> 
> In the Xamarin.Forms version of this app, I used SkiaSharp, which supports getting a path from a string. Maybe try to look at [that solution](https://github.com/RadekVyM/Navbar-Animation-2/blob/7cda52cc3747d847af8990f0043938d0592b24cd/src/NavbarAnimation2/NavbarAnimation2/Views/Controls/TabSvgView.xaml.cs).

Thank you for your reply. Have a good day!

**Comment by GangHyeok-Ji** [comment]
Hi @RadekVyM,

I'm looking at the source I told you last time, but I'm asking you again because the result didn't come out.

When I transformed the title passed in the CanvasViewPaintSurface  function, the area appears inverted.

M4.86035 -2.63965C4.86035 -1.94531 4.32129 -1.32129 3.60059 -1.32129C2.87988 -1.32129 2.34082 -1.94531 2.34082 -2.63965C2.34082 -3.33691 2.87988 -3.96094 3.60059 -3.96094C4.32129 -3.96094 4.86035 -3.33691 4.86035 -2.63965ZM6.65918 -5.2793L4.86035 -5.2793L4.86035 -4.64355C4.3916 -5.2207 3.7207 -5.41113 3.04688 -5.41113C1.54688 -5.41113 0.418945 -4.10449 0.418945 -2.63965C0.418945 -1.1748 1.54688 0.120117 3.04688 0.120117C3.7207 0.120117 4.5 -0.0966797 4.86035 -0.635742L4.86035 0L6.65918 0L6.65918 -5.2793ZM9.89958 -2.63965C9.89958 -3.33691 10.4386 -3.96094 11.1593 -3.96094C11.8801 -3.96094 12.4191 -3.33691 12.4191 -2.63965C12.4191 -1.94531 11.8801 -1.32129 11.1593 -1.32129C10.4386 -1.32129 9.89958 -1.94531 9.89958 -2.63965ZM9.89958 0L9.89958 -0.635742C10.2599 -0.0966797 11.0275 0.120117 11.7131 0.120117C13.2131 0.120117 14.341 -1.1748 14.341 -2.63965C14.341 -4.10449 13.2131 -5.41113 11.7131 -5.41113C11.0275 -5.41113 10.3683 -5.2207 9.89958 -4.64355L9.89958 -9L8.10075 -9L8.10075 0L9.89958 0ZM20.3763 -3.68262C20.221 -4.89551 19.2015 -5.41113 17.807 -5.41113C16.055 -5.41113 15.2289 -4.81055 15.2289 -3.73242C15.2289 -1.81055 18.6478 -2.68945 18.6478 -1.57324C18.6478 -1.2832 18.2992 -1.12793 17.8919 -1.12793C17.4964 -1.12793 16.7874 -1.1748 16.7874 -1.96875L15.0003 -1.96875C15.097 -0.46875 16.2835 0.120117 17.8568 0.120117C19.3919 0.120117 20.4613 -0.336914 20.4613 -1.58496C20.4613 -3.81738 17.0394 -3.05859 17.0394 -3.80273C17.0394 -4.11621 17.4115 -4.29492 17.7601 -4.29492C18.1087 -4.29492 18.5511 -4.16309 18.6126 -3.68262L20.3763 -3.68262ZM23.1727 -3.27539C23.1727 -3.27539 23.2313 -4.25977 24.3592 -4.25977C25.452 -4.25977 25.5369 -3.27539 25.5369 -3.27539L23.1727 -3.27539ZM27.2655 -2.75977C27.2655 -4.45312 25.9324 -5.41113 24.3241 -5.41113C22.5487 -5.41113 21.2391 -4.29492 21.2391 -2.63965C21.2391 -0.960938 22.4989 0.120117 24.3241 0.120117C25.7274 0.120117 26.8553 -0.577148 27.1688 -1.96875L25.3319 -1.96875C25.3201 -1.58496 24.9246 -1.16309 24.2889 -1.16309C23.5799 -1.16309 23.1492 -1.81055 23.1492 -2.42285L27.2508 -2.42285C27.2508 -2.53125 27.2655 -2.65137 27.2655 -2.75977ZM33.816 -3C33.816 -4.44141 33.2389 -5.41113 31.8238 -5.41113C31.1295 -5.41113 30.5641 -5.10059 30.2037 -4.64355L30.2037 -5.29102L28.4049 -5.29102L28.4049 0L30.2037 0L30.2037 -2.63965C30.2037 -3.36035 30.649 -3.96094 31.2115 -3.96094C31.777 -3.96094 32.0172 -3.62402 32.0172 -3L32.0172 0L33.816 0L33.816 -3ZM37.7752 -4.00781C38.3992 -4.00781 38.7976 -3.68262 38.8211 -3.16699L40.6082 -3.16699C40.5232 -4.3916 39.4334 -5.41113 37.7166 -5.41113C35.9529 -5.41113 34.7752 -4.15137 34.7752 -2.63965C34.7752 -1.12793 35.8797 0.120117 37.7166 0.120117C39.325 0.120117 40.3914 -0.791016 40.573 -1.96875L38.8211 -1.96875C38.7596 -1.48828 38.3289 -1.24805 37.7752 -1.24805C36.9373 -1.24805 36.6971 -2.01562 36.6971 -2.62793C36.6971 -3.22852 36.9607 -4.00781 37.7752 -4.00781ZM43.3328 -3.27539C43.3328 -3.27539 43.3914 -4.25977 44.5193 -4.25977C45.6121 -4.25977 45.6971 -3.27539 45.6971 -3.27539L43.3328 -3.27539ZM47.4256 -2.75977C47.4256 -4.45312 46.0926 -5.41113 44.4842 -5.41113C42.7088 -5.41113 41.3992 -4.29492 41.3992 -2.63965C41.3992 -0.960938 42.659 0.120117 44.4842 0.120117C45.8875 0.120117 47.0154 -0.577148 47.3289 -1.96875L45.492 -1.96875C45.4803 -1.58496 45.0848 -1.16309 44.449 -1.16309C43.7401 -1.16309 43.3094 -1.81055 43.3094 -2.42285L47.4109 -2.42285C47.4109 -2.53125 47.4256 -2.65137 47.4256 -2.75977ZM53.4605 -3.68262C53.3053 -4.89551 52.2857 -5.41113 50.8912 -5.41113C49.1393 -5.41113 48.3131 -4.81055 48.3131 -3.73242C48.3131 -1.81055 51.732 -2.68945 51.732 -1.57324C51.732 -1.2832 51.3834 -1.12793 50.9762 -1.12793C50.5807 -1.12793 49.8717 -1.1748 49.8717 -1.96875L48.0846 -1.96875C48.1812 -0.46875 49.3678 0.120117 50.941 0.120117C52.4762 0.120117 53.5455 -0.336914 53.5455 -1.58496C53.5455 -3.81738 50.1236 -3.05859 50.1236 -3.80273C50.1236 -4.11621 50.4957 -4.29492 50.8443 -4.29492C51.193 -4.29492 51.6353 -4.16309 51.6969 -3.68262L53.4605 -3.68262Z

Is there anything else I missed besides the ToSvgPathData()  function?
