### ISSUE TITLE
Top Navigationbar

### ISSUE THREAD

**Issue by Blinchik91** [RadekVyM/Navbar-Animation-2#2]
Hello,

How do I enable the top navigation bar for this example?
I tried a few things but nothing helped.... 
The normal shell shows it.

**Comment by RadekVyM** [comment]
Hi @Blinchik91,
[SimpleShell](https://github.com/RadekVyM/SimpleToolkit/tree/main/docs/SimpleToolkit.SimpleShell) does not support default navigation bar. You have to create your own as with other navigation controls.

**Comment by Blinchik91** [comment]
@RadekVyM 
Would it be possible to implement this default, I actually only wanted to customize the navigation, but not the navigation bar?

**Comment by RadekVyM** [comment]
@Blinchik91
In theory it should be possible, but I have not added this feature to [SimpleShell](https://github.com/RadekVyM/SimpleToolkit/tree/main/docs/SimpleToolkit.SimpleShell) because I have not needed it yet. It is not that difficult to implement custom app bar.
